export function createTodo(name: number | string | null = null): Todo {
  const id: number = Math.floor(Math.random() * Date.now());
  const defaultOptions = {
    isComplete: false,
    isEditing: false,
  };

  if (typeof name === "number") {
    return {
      id: name + 1,
      text: (name + 1).toString(),
      ...defaultOptions,
    };
  }

  if (typeof name === "string") {
    return {
      id,
      text: name,
      ...defaultOptions,
    };
  }

  return {
    id,
    text: `Generated by ${id}`,
    ...defaultOptions,
  };
}
