export function createTodo(name?: string): Todo {
  const id: number = Math.floor(Math.random() * Date.now());
  const defaultOptions = {
    isComplete: false,
  };

  if (name) {
    return {
      id,
      text: name,
      ...defaultOptions,
    };
  }

  return {
    id,
    text: `Generated by ${id}`,
    ...defaultOptions,
  };
}

export function generateTodos(amount: number) {
  return Array.from({ length: amount }, () => createTodo());
}
