export function createTodo(name?: string): Todo {
  const id: number = Math.floor(Math.random() * Date.now());

  return {
    id,
    text: name ? name : `Generated by ${id}`,
    isComplete: false,
  };
}

export function generateTodos(amount: number) {
  return Array.from({ length: amount }, () => createTodo());
}
